# Generated by Django 2.0 on 2017-12-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=60)),
                ('file_link', models.FileField(upload_to='upload/')),
            ],
        ),
    ]
